/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ReferentielRouteImport } from './routes/referentiel'
import { Route as SquadsRouteImport } from './routes/squads'
import { Route as DemandesIdIndexRouteImport } from './routes/demandes/$id/index'
import { Route as DemandesIdProcessusRouteImport } from './routes/demandes/$id/processus'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferentielRoute = ReferentielRouteImport.update({
  id: '/referentiel',
  path: '/referentiel',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadsRoute = SquadsRouteImport.update({
  id: '/squads',
  path: '/squads',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandesIdIndexRoute = DemandesIdIndexRouteImport.update({
  id: '/demandes/$id/',
  path: '/demandes/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandesIdProcessusRoute = DemandesIdProcessusRouteImport.update({
  id: '/demandes/$id/processus',
  path: '/demandes/$id/processus',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/parametres': typeof ParametresRoute
  '/pipeline': typeof PipelineRoute
  '/referentiel': typeof ReferentielRoute
  '/squads': typeof SquadsRoute
  '/demandes/$id/processus': typeof DemandesIdProcessusRoute
  '/demandes/$id/': typeof DemandesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/parametres': typeof ParametresRoute
  '/pipeline': typeof PipelineRoute
  '/referentiel': typeof ReferentielRoute
  '/squads': typeof SquadsRoute
  '/demandes/$id/processus': typeof DemandesIdProcessusRoute
  '/demandes/$id': typeof DemandesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/parametres': typeof ParametresRoute
  '/pipeline': typeof PipelineRoute
  '/referentiel': typeof ReferentielRoute
  '/squads': typeof SquadsRoute
  '/demandes/$id/processus': typeof DemandesIdProcessusRoute
  '/demandes/$id/': typeof DemandesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/parametres'
    | '/pipeline'
    | '/referentiel'
    | '/squads'
    | '/demandes/$id/processus'
    | '/demandes/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/parametres'
    | '/pipeline'
    | '/referentiel'
    | '/squads'
    | '/demandes/$id/processus'
    | '/demandes/$id'
  id:
    | '__root__'
    | '/'
    | '/parametres'
    | '/pipeline'
    | '/referentiel'
    | '/squads'
    | '/demandes/$id/processus'
    | '/demandes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParametresRoute: typeof ParametresRoute
  PipelineRoute: typeof PipelineRoute
  ReferentielRoute: typeof ReferentielRoute
  SquadsRoute: typeof SquadsRoute
  DemandesIdProcessusRoute: typeof DemandesIdProcessusRoute
  DemandesIdIndexRoute: typeof DemandesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referentiel': {
      id: '/referentiel'
      path: '/referentiel'
      fullPath: '/referentiel'
      preLoaderRoute: typeof ReferentielRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squads': {
      id: '/squads'
      path: '/squads'
      fullPath: '/squads'
      preLoaderRoute: typeof SquadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandes/$id/': {
      id: '/demandes/$id/'
      path: '/demandes/$id'
      fullPath: '/demandes/$id/'
      preLoaderRoute: typeof DemandesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandes/$id/processus': {
      id: '/demandes/$id/processus'
      path: '/demandes/$id/processus'
      fullPath: '/demandes/$id/processus'
      preLoaderRoute: typeof DemandesIdProcessusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParametresRoute: ParametresRoute,
  PipelineRoute: PipelineRoute,
  ReferentielRoute: ReferentielRoute,
  SquadsRoute: SquadsRoute,
  DemandesIdProcessusRoute: DemandesIdProcessusRoute,
  DemandesIdIndexRoute: DemandesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
